- name: Create bin directory
  file:
    path: "{{ paths.bin }}"
    state: directory
    recurse: yes

- name: Check if yay is already installed
  stat:
    path: "{{ paths.bin }}/yay/PKGBUILD"
  register: yay_pkgbuild

- name: Clone yay repository (https://aur.archlinux.org/yay.git)
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ paths.bin }}/yay"
  when: not yay_pkgbuild.stat.exists


- name: Install yay
  command: "makepkg -si --noconfirm"
  args:
    chdir: "{{ paths.bin }}/yay"
  when: not yay_pkgbuild.stat.exists
