- name: Create Fish config directory
  file:
    path: "{{ paths.config }}/fish"
    state: directory
    recurse: yes

- name: Link Fish config
  file:
    src: "{{ role_path }}/files/config.fish"
    dest: "{{ paths.config }}/fish/config.fish"
    state: link

- name: Link Fish functions
  file:
    src: "{{ role_path }}/files/functions"
    dest: "{{ paths.config }}/fish/functions"
    state: link
