- name: Install Arch core dependencies
  pacman:
    name: "{{ packages.global + packages.arch.core }}"
    state: present
  become: true

- name: Install Arch AUR dependencies
  yay:
    name: "{{ packages.arch.aur }}"
    state: present
  become: true
