- name: Install Arch dependencies
  pacman:
    name: "{{ packages.global + packages.arch.core }}"
    state: present
  become: true

- name: Create bin directory
  file:
    path: "{{ paths.bin }}"
    state: directory
    recurse: yes
