- name: Create swap, backup, undo and autoload directories for NeoVim
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ paths.config }}/nvim/undo"
    - "{{ paths.config }}/nvim/backup"
    - "{{ paths.config }}/nvim/swap"
    - "{{ paths.home }}/.local/share/nvim/site/autoload"

- name: Create swap, backup, undo and autoload directories for Vim
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ paths.home }}/.vim/undo"
    - "{{ paths.home }}/.vim/backup"
    - "{{ paths.home }}/.vim/swap"
    - "{{ paths.home }}/.vim/autoload"

- name: Install Vim-Plug for NeoVim
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ paths.home }}/.local/share/nvim/site/autoload/plug.vim"

- name: Install Vim-Plug for Vim
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ paths.home }}/.vim/autoload/plug.vim"

- name: Link NeoVim config
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ paths.config }}/nvim/init.vim"
    state: link

- name: Link Vim config
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ paths.home }}/.vimrc"
    state: link

# - import_tasks: macos.yml
#   when: ansible_os_family == "Darwin"

# - import_tasks: arch.yml
#   when: ansible_os_family == "ArchLinux"
